apiVersion: v1
kind: ConfigMap
metadata:
  name: ngxapi
  labels:
    app: ngxapi
data:
  NODE_TLS_REJECT_UNAUTHORIZED: '0'
  DOMAIN_URL: 'https://ngxapi.traefik.k8s'
  TYPEORM_HOST: ngxdb-postgresql
  TYPEORM_PORT: '5432'
  TYPEORM_DATABASE: postgres
  TYPEORM_USERNAME: postgres
  TYPEORM_LOGGING: 'false'
  OIDC_ISSUER_URL: 'https://keycloak.traefik.k8s/auth/realms/ngx'
  OIDC_JWKS_URL: 'http://keycloak-headless:8080/auth/realms/ngx/protocol/openid-connect/certs'
  OIDC_CLIENT_ID: ngxapi
  EMAIL_HOST: mail.google.com
  EMAIL_PORT: '25'
  EMAIL_SECURE: 'false'
  EMAIL_AUTH_USER: auth_user
  EMAIL_FROM: '"sumo demo" <sumo@demo.com>'
  VAPID_PUBLIC_KEY: 'BAJq-yHlSNjUqKW9iMY0hG96X9WdVwetUFDa5rQIGRPqOHKAL_fkKUe_gUTAKnn9IPAltqmlNO2OkJrjdQ_MXNg'
