# Default values for anginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


## Image
image:
  repository: nginxinc/nginx-unprivileged
  tag: 1.19.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

securityContext:
  runAsUser: 1001

## Pod annotations
podAnnotations: {}

serverName: localhost

## Service
service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  port: 80
  nodePort: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: anginx.local
      paths: [/]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - anginx.local

## Create NetworkPolicy resources.
networkPolicy:
  enabled: false
## If you do want to specify egress, uncomment the following
#  egress:
#    - to:
#        - ipBlock: # Allow nodeapp to talk to external servers
#            cidr: 0.0.0.0/0
#    - ports: # Allow nodeapp to talk with the api server
#        - port: 6443
#          protocol: TCP
#        - port: 6443
#          protocol: UDP

## Create HorizontalPodAutoscaler object.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Create GKE Managed Certificate resource.
managedcertificate:
  enabled: false
#  host: www.mydomain.com
