language: node_js
node_js: # will use latest stable node
  - '11'

#addons:
#  chrome: stable

cache: # global caching
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

env:
  - NODE_ENV=mock

stages:
#  - lint
#  - test
#  - build
#  - name: release
##    if: branch = master AND type IN (push)
#    if: branch = master AND tag IS present
  - name: deploy
    if: branch = master AND type != pull_request
  - name: docs
    if: branch = master AND tag IS present

jobs:
  include:
#    - stage: lint
#      script: yarn lint

#    - stage: test # unit test
#      script:
#        - yarn test:ci

#    - stage: test # e2e test
#      script:
#        - yarn e2e:ci

#    - stage: build
#      before_script: yarn prebuild
#      script:
#        - yarn build:mock

#    - stage: release # semantic release - create changelog
#      if: branch = master AND tag IS present
#      script: skip
#      deploy:
#        provider: script
#        script: yarn release
#        skip-cleanup: true

#    - stage: release # github release
#      if: branch = master AND tag IS present
#      script: yarn build:mock
#      before_deploy:
#        - tar czvf webapp.tar.gz -C dist/apps/webapp .
#      deploy:
#        - provider: releases
#          api_key: $GITHUB_TOKEN
#          file: './webapp.tar.gz'
#          skip_cleanup: true

    - stage: deploy
      script: yarn build:mock
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        target-branch: gh-pages
        local_dir: dist/apps/webapp
        skip-cleanup: true
        keep-history: true

    - stage: docs
      script: yarn doc:build
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        target-branch: docs
        local_dir: docs
        skip-cleanup: true
        keep-history: true
