envSecrets:
-   name: ENC[AES256_GCM,data:j49m+hIvwADspA4SyrQ7Vw==,iv:vi8eAv6qE6HFuAHmhdG1eUaf/VqE9UnY1njxBtfnxNg=,tag:o1CCX8ao/A12NfMSPEmveg==,type:str]
    value: ENC[AES256_GCM,data:oCiz15CGTe1rjg8=,iv:Hz5rnBYj9vGHVMZf1dsISs7gMMM5O91lEIJjO89S7lM=,tag:lP+cSv9/st4wZ9dY7hDoQw==,type:str]
-   name: ENC[AES256_GCM,data:5+uBxpn+Q2UeC2uXhF5k,iv:qhG0kfaAmMha8CyTIggUX925NwDsql/zm9vKkwbiMxY=,tag:YaEPKlbei5Szs2eloINauQ==,type:str]
    value: ENC[AES256_GCM,data:0nsAEGhBRMqx,iv:0XQtpG0AqUja0qigrv9TiMi0CbltRMH7kJd/Twcyy4o=,tag:tgUkpguTZYYYOba/QwTS2A==,type:str]
-   name: ENC[AES256_GCM,data:/Kts0rswJFSr7HWwYAhW96M=,iv:v8FuthP6aMtVS4SkoCxUzaT/N3hM9PI8m943sj5UgA0=,tag:MDtHO9f2aDqep4Tjv5Am0g==,type:str]
    value: ENC[AES256_GCM,data:cw9KHNy1A/s0rrUzCwRX6DEifN6vRgrYWvpJABCBrF6DnnlmoqyaCuCt6w==,iv:AU+WjTK3jldT5Uz4XWQ99t2P2/gZuJiun3RFIYJgpGU=,tag:FwaipJA+KJZGDtZ+kVWmAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-04-02T08:47:48Z'
    mac: ENC[AES256_GCM,data:XcliwQ7ra8ucTvf8+vQoE2S0lxziPqq/UWa2P288CkXvNiaJZ8q4WFxjGjoEyjXCOtfzvbwhRqaMUg/qd1igf18iEXS9T6urRvTklQkQmczqU3d05CGqJQD5bw6+OchtvmMkm8L6sgyTVKfO5huL+KSL/VMSiW+VtbFrHGsXlyE=,iv:w3a4FDMIPS2BQehta7Byn8QZOSMGsTCpAV+NeNdqzxA=,tag:x7KoMryyAVl2zeDXfOZMpw==,type:str]
    pgp:
    -   created_at: '2019-04-02T08:47:48Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA0lc+u+GLoPGAQgAbVswSTLIYu/XClfXGVZ65wn/Rxhuq0/yQRlf0NnUXuQz
            B+p41j6i6U2E/ScD+/GKRLbOeQRBRFxcdZ6M3ZwKdkuY2kkjSR0BLHg5M/TiXyVr
            vE12ZHTqVmFRWLFZjMyjKRkWbxDXJ09coLe+hQNHqIv3pzuEdAuLefDs/Q/mH8IK
            U1VE2fNmf6TsS6C3Aw1oxslNqdnyEFl8c/H/Om8QdcEF5YjWZ6NTmjXB7ajMawnA
            0FYHmVqO/aPFemIqoSHUNbDcCzx5VsSzjf+8uFtrVFaRNB1Pl4Mqxhc+VMliV8ad
            sLSCAbQaAYtetdJvFT+J9AYIkOHlS9XsPZRwYL7v+tLgAeQPm1PbZV42fl0d7ZGM
            FnfV4d5b4PDgXeEs1uA84jawCbrgOOWVblOnho9I8fC0HuY6m4nAGRndyCQ3++u0
            5QAA6lzH++Ac5AC3iIpeWICIn3Fl7uP+K9vipVZ1BuFWawA=
            =Se54
            -----END PGP MESSAGE-----
        fp: 438F624ADE96A9DE20DE7C5672EB37BA9AB0F7E7
    unencrypted_suffix: _unencrypted
    version: 3.2.0
