test:
  enabled: false

resources:
  limits:
     cpu: 100m
     memory: 128Mi
  requests:
     cpu: 100m
     memory: 128Mi

image:
  repository: xmlking/ngxweb
  tag: 2.0.0-SNAPSHOT
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 1001

serverName: ngxweb.traefik.k8s

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "true"
  hosts:
    - host: ngxweb.traefik.k8s
      paths: [/]
  tls:
    - secretName: keycloak-secrets-tls
      hosts:
        - ngxweb.traefik.k8s
