apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kashmora-ingress
  labels:
    app: keycloak
  annotations:
#    kubernetes.io/ingress.global-static-ip-name: kashmora-static-ip
    kubernetes.io/ingress.global-static-ip-name: keycloak-ip-address
    networking.gke.io/managed-certificates: "ngxweb-anginx,ngxapi-nodeapp,keycloak"
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: ngxweb-anginx
    servicePort: http
  rules:
    - host: keycloak.kashmora.com
      http:
        paths:
          - backend:
              serviceName: keycloak-http
              servicePort: http
    - host: api.kashmora.com
      http:
        paths:
          - backend:
              serviceName: ngxapi-nodeapp
              servicePort: http
    - host: kashmora.com
      http:
        paths:
          - backend:
              serviceName: ngxweb-anginx
              servicePort: http
